volumes:
  auth_postgresql:

networks:
  auth_backend:
    driver: "bridge"

services:
  jwt_auth:
    build:
      dockerfile: docker/prod/app/Dockerfile
    container_name: app_jwt_auth

    ports:
      - "8000:8000"